universe = vanilla
executable = pipeline_stationary_cameras.sh
arguments = /cluster/research-groups/wehrwein/zoo/konnor/colmap/zoo_reconstruction/colmap-lightglue

request_cpus = 8
request_memory = 64GB
request_gpus = 1
gpus_minimum_memory = 80000

+WantH100 = True
+WantPreempt = True

output = logs/output.log
error = logs/error.log
log = logs/condor.log

getenv = true
initialdir = /cluster/research-groups/wehrwein/zoo/konnor/colmap/zoo_reconstruction/colmap-lightglue

queue
