universe = vanilla
executable = pipeline_stationary_cameras.sh
arguments = /cluster/research-groups/wehrwein/zoo/konnor/colmap/zoo_reconstruction/colmap-lightglue

request_cpus = 4
request_memory = 32GB
request_gpus = 1

request_gpus = 1

output = logs/output.log
error = logs/error.log
log = logs/condor.log

getenv = true
initialdir = /cluster/research-groups/wehrwein/zoo/konnor/colmap/zoo_reconstruction/colmap-lightglue

queue
