universe = vanilla
executable = test_handheld_only.sh
arguments = .

initialdir = /cluster/research-groups/wehrwein/zoo/konnor/colmap/zoo_reconstruction/colmap-lightglue

request_cpus = 4
request_memory = 32GB
request_gpus = 1
request_disk = 20GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = handheld
transfer_output_files = database.db, sparse_test

output = logs/output_test.log
error = logs/error_test.log
log = logs/condor_test.log

getenv = False

queue
