universe = vanilla
executable = pipeline_stationary_cameras.sh
arguments = .

initialdir = /cluster/research-groups/wehrwein/zoo/konnor/colmap/zoo_reconstruction/colmap/lightglue_v1

request_cpus = 4
request_memory = 32GB
request_gpus = 1
request_disk = 20GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = lightglue_match.py, ../stationary, ../handheld
transfer_output_files = database.db, sparse

output = logs/output.log
error = logs/error.log
log = logs/condor.log

getenv = False

queue
