universe = vanilla
executable = dense_handheld.sh
arguments = .

initialdir = /cluster/research-groups/wehrwein/zoo/konnor/colmap/zoo_reconstruction/colmap/colmap_test_pipeline

request_cpus = 4
request_memory = 32GB
request_gpus = 1
request_disk = 20GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = ../handheld
transfer_output_files = database.db, sparse, dense

output = logs/dense_output.log
error = logs/dense_error.log
log = logs/dense_condor.log

getenv = False

queue
