#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "opencv-contrib-python",
#   "numpy",
#   "Pillow",
# ]
# ///
"""
visualize_apriltags.py

Detect the custom Tag36h11 tags (generated by generate_apriltags.py) in a
folder of images and save annotated copies with neon-green corner borders and
tag-ID labels overlaid.

Uses the same codes and spiral bit-ordering as generate_apriltags.py to build
a custom OpenCV ArUco dictionary so detection matches exactly what was printed.

Usage:
    uv run visualize_apriltags.py --images <folder> [--output-dir <folder>]
"""

import argparse
import sys
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageOps
from tag_dict import build_custom_dictionary


# ---------------------------------------------------------------------------
# Drawing
# ---------------------------------------------------------------------------
NEON_GREEN = (20, 255, 57)
LABEL_FONT = cv2.FONT_HERSHEY_SIMPLEX
LABEL_SCALE = 1.2
LABEL_THICKNESS = 3


def annotate_image(img_bgr: np.ndarray, corners: list, ids) -> np.ndarray:
    out = img_bgr.copy()
    if ids is None:
        return out

    # Scale annotation sizes proportionally to the image resolution
    img_diag = (img_bgr.shape[0] ** 2 + img_bgr.shape[1] ** 2) ** 0.5
    scale = max(1.0, img_diag / 3000)
    line_thickness = max(2, int(3 * scale))
    circle_radius = max(4, int(8 * scale))
    font_scale = max(0.8, 1.2 * scale)
    font_thickness = max(2, int(3 * scale))

    for corner, tag_id in zip(corners, ids.flatten()):
        pts = corner[0].astype(int)  # shape (4, 2)

        cv2.polylines(out, [pts.reshape((-1, 1, 2))], isClosed=True,
                      color=NEON_GREEN, thickness=line_thickness)
        for cx, cy in pts:
            cv2.circle(out, (cx, cy), radius=circle_radius,
                       color=NEON_GREEN, thickness=-1)

        label = f"ID {tag_id}"
        tl, tr = pts[0], pts[1]
        top_mid = ((tl[0] + tr[0]) // 2, (tl[1] + tr[1]) // 2)
        (tw, th), baseline = cv2.getTextSize(label, LABEL_FONT, font_scale, font_thickness)
        lx = top_mid[0] - tw // 2
        ly = top_mid[1] - th - int(10 * scale)
        pad = int(6 * scale)
        cv2.rectangle(out,
                      (lx - pad, ly - th - pad),
                      (lx + tw + pad, ly + baseline + pad),
                      (0, 0, 0), thickness=-1)
        cv2.putText(out, label, (lx, ly),
                    LABEL_FONT, font_scale, NEON_GREEN, font_thickness,
                    lineType=cv2.LINE_AA)
    return out


# ---------------------------------------------------------------------------
# Processing
# ---------------------------------------------------------------------------

def load_image_exif_corrected(path: Path) -> np.ndarray:
    """Load image and apply EXIF orientation correction."""
    pil = Image.open(path)
    pil = ImageOps.exif_transpose(pil)
    return np.array(pil)[:, :, ::-1]  # RGB→BGR


def detect(gray: np.ndarray, dictionary: cv2.aruco.Dictionary,
           params: cv2.aruco.DetectorParameters):
    detector = cv2.aruco.ArucoDetector(dictionary, params)
    return detector.detectMarkers(gray)


def process_folder(images_dir: Path, output_dir: Path, exts: list[str]) -> None:
    print("Building custom tag dictionary...", end=" ", flush=True)
    dictionary = build_custom_dictionary()
    print("done.")

    params = cv2.aruco.DetectorParameters()
    # Relaxed params to handle real-world photos
    params.minMarkerPerimeterRate = 0.01
    params.adaptiveThreshWinSizeMin = 3
    params.adaptiveThreshWinSizeMax = 53
    params.adaptiveThreshWinSizeStep = 10
    params.errorCorrectionRate = 1.0

    image_paths: list[Path] = []
    for ext in exts:
        image_paths.extend(sorted(images_dir.glob(f"*.{ext}")))
        image_paths.extend(sorted(images_dir.glob(f"*.{ext.upper()}")))

    if not image_paths:
        sys.exit(f"[ERROR] No images found in {images_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"Processing {len(image_paths)} image(s) → {output_dir}")

    for idx, img_path in enumerate(image_paths, start=1):
        img = load_image_exif_corrected(img_path)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Enhance contrast before detection
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        gray_eq = clahe.apply(gray)

        corners, ids, _ = detect(gray_eq, dictionary, params)
        id_list = ids.flatten().tolist() if ids is not None else []
        print(f"  [{idx}/{len(image_paths)}] {img_path.name}  →  {len(id_list)} tag(s): {id_list}")

        annotated = annotate_image(img, corners, ids)
        cv2.imwrite(str(output_dir / img_path.name), annotated)

    print(f"\nDone. Annotated images saved to: {output_dir.resolve()}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Detect custom AprilTags and save images with neon-green annotations."
    )
    parser.add_argument("--images", required=True, type=Path,
                        help="Folder of input images.")
    parser.add_argument("--output-dir", type=Path, default=None,
                        help="Where to save annotated images (default: <images>/vis_apriltags/).")
    parser.add_argument("--exts", nargs="+", default=["jpg", "jpeg", "png"],
                        help="File extensions to process.")
    args = parser.parse_args()

    if not args.images.is_dir():
        sys.exit(f"[ERROR] Not a directory: {args.images}")

    output_dir = args.output_dir or (args.images / "vis_apriltags")
    process_folder(args.images, output_dir, args.exts)


if __name__ == "__main__":
    main()
